[project]
name = "nanogenie"
version = "0.1.0"
description = "A small implementation of the world model architecture described in Genie 1."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
]
