[project]
name = "nanogenie"
version = "0.1.0"
description = "A small implementation of the world model architecture described in Genie 1."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.3.5",
    "pytest>=9.0.1",
    "torch>=2.9.1",
]
